/**
 * @file          boolean_storage.h
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_BOOLEAN_STORAGE_H
#define INGOT_BOOLEAN_STORAGE_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Boolean bitfield storage: {{ bool.num_keys }} keys in {{ bool.num_words }} word(s) */
#define BOOLEAN_STORAGE_NUM_KEYS {{ bool.num_keys }}U

bool BooleanStorage_SetKey(uint32_t key, bool value);
bool BooleanStorage_GetKey(uint32_t key, bool *result);

#ifdef __cplusplus
}
#endif

#endif /* INGOT_BOOLEAN_STORAGE_H */