/* Generated by ingot v{{ version }} — do not edit */
#include <stddef.h>
#include "boolean_storage.h"
#include "core/jenkins_hash.h"

#define SetBit(A, k)   ( A[(k) / 32] |=  (1U << ((k) % 32)) )
#define ClearBit(A, k) ( A[(k) / 32] &= ~(1U << ((k) % 32)) )
#define TestBit(A, k)  ( A[(k) / 32] &   (1U << ((k) % 32)) )

static uint32_t bool_storage[{{ bool.num_words }}] = {
    {{ bool.init_table_str }}
};

#define BOOL_HASH_SEED_1 {{ bool.seed1 }}U
#define BOOL_HASH_SEED_2 {{ bool.seed2 }}U
#define BOOL_HASH_G_SIZE {{ bool.g_size }}U

#define BOOL_HASH_INDEX(key, seed) \
    bool_G[jenkins_hash(seed, key) % BOOL_HASH_G_SIZE]

static const {{ bool.g_c_type }} bool_G[BOOL_HASH_G_SIZE] = {
    {{ bool.g_table_str }}
};

bool BooleanStorage_SetKey(uint32_t key, bool value)
{
    uint32_t index = (BOOL_HASH_INDEX(key, BOOL_HASH_SEED_1)
                    + BOOL_HASH_INDEX(key, BOOL_HASH_SEED_2))
                    % BOOLEAN_STORAGE_NUM_KEYS;
    if (value) {
        SetBit(bool_storage, index);
    } else {
        ClearBit(bool_storage, index);
    }
    return true;
}

bool BooleanStorage_GetKey(uint32_t key, bool *result)
{
    if (result == NULL) {
        return false;
    }
    uint32_t index = (BOOL_HASH_INDEX(key, BOOL_HASH_SEED_1)
                    + BOOL_HASH_INDEX(key, BOOL_HASH_SEED_2))
                    % BOOLEAN_STORAGE_NUM_KEYS;
    *result = TestBit(bool_storage, index) != 0;
    return true;
}