/* Generated by ingot v{{ version }} — do not edit */
#include <string.h>
#include "dm.h"
#include "key_definitions.h"
{% if has_bool %}
#include "storage/boolean_storage.h"
{% endif %}
{% if has_integers %}
#include "storage/integer_storage.h"
{% endif %}
{% if has_ro_strings or has_rw_strings %}
#include "storage/string_storage.h"
{% endif %}
{% if has_persistence %}
#include "storage/persistence_storage.h"
{% endif %}
{% if target.has_mutex %}
{{ target.mutex_include }}
{% endif %}

static bool dm_initialized = false;
{% if not no_events %}
static DataModel_Event_Callback dm_event_callback = NULL;
{% endif %}
{% if target.has_mutex %}
{{ target.mutex_decl }}
{% endif %}
{% if not no_events %}

void DataModel_Initialize(DataModel_Event_Callback event_callback)
{
    dm_event_callback = event_callback;
{% else %}

void DataModel_Initialize(void)
{
{% endif %}
{% if target.has_mutex and target.mutex_init %}
    {{ target.mutex_init }}
{% endif %}
    dm_initialized = true;
}

void DataModel_TearDown(void)
{
    dm_initialized = false;
{% if not no_events %}
    dm_event_callback = NULL;
{% endif %}
{% if target.has_mutex and target.mutex_destroy %}
    {{ target.mutex_destroy }}
{% endif %}
}

DM_RETURN_CODE DataModel_SetIntegralTypeByKey(uint32_t key, dm_val_t inval)
{
    DM_RETURN_CODE retval;
    bool storage_result;
    dm_val_t prev = { 0 };

    if (!dm_initialized) {
        return DM_RETURN_CODE_NOT_INITIALIZED;
    }
    if (DM_IS_KEY_READONLY(key)) {
        return DM_RETURN_CODE_SET_ON_READONLY_KEY;
    }
{% if target.has_mutex %}

    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_lock }};
    }
{% endif %}

    switch (DM_KEY_GET_TYPE(key)) {
{% if has_bool %}
    case DM_KEY_TYPE_BOOL:
        storage_result = BooleanStorage_GetKey(key, &prev.bval);
        if (!storage_result) { retval = DM_RETURN_CODE_STORAGE_LOOKUP_FAILURE; break; }
        if (prev.bval == inval.bval) { retval = DM_RETURN_CODE_SET_VALUE_UNCHANGED; break; }
        storage_result = BooleanStorage_SetKey(key, inval.bval);
        if (storage_result) {
            retval = DM_RETURN_CODE_SUCCESS;
        } else {
            retval = DM_RETURN_CODE_STORAGE_LOOKUP_FAILURE;
        }
        break;
{% endif %}
{% for t in int_types %}
    case {{ t.type_enum }}:
        storage_result = {{ t.get_fn }}(key, &prev.{{ t.val_field }});
        if (!storage_result) { retval = DM_RETURN_CODE_STORAGE_LOOKUP_FAILURE; break; }
        if (prev.{{ t.val_field }} == inval.{{ t.val_field }}) { retval = DM_RETURN_CODE_SET_VALUE_UNCHANGED; break; }
        storage_result = {{ t.set_fn }}(key, inval.{{ t.val_field }});
        if (storage_result) {
            retval = DM_RETURN_CODE_SUCCESS;
        } else {
            retval = DM_RETURN_CODE_STORAGE_LOOKUP_FAILURE;
        }
        break;
{% endfor %}
    default:
        retval = DM_RETURN_CODE_KEY_TYPE_INCORRECT;
        break;
    }
{% if target.has_mutex %}

    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_unlock }};
    }
{% endif %}

{% if not no_events %}
    if (retval == DM_RETURN_CODE_SUCCESS && dm_event_callback != NULL) {
        dm_event_callback(key);
    }
{% endif %}

    return retval;
}

dm_val_t DataModel_GetIntegralTypeByKey(uint32_t key)
{
    dm_val_t val = { 0 };

    if (!dm_initialized) {
        return val;
    }
{% if target.has_mutex %}

    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_lock }};
    }
{% endif %}

    switch (DM_KEY_GET_TYPE(key)) {
{% if has_bool %}
    case DM_KEY_TYPE_BOOL:
        BooleanStorage_GetKey(key, &val.bval);
        break;
{% endif %}
{% for t in int_types %}
    case {{ t.type_enum }}:
        {{ t.get_fn }}(key, &val.{{ t.val_field }});
        break;
{% endfor %}
    default:
        break;
    }
{% if target.has_mutex %}

    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_unlock }};
    }
{% endif %}

    return val;
}

/* ---- Typed convenience setters ---- */
{% if has_bool %}

DM_RETURN_CODE DataModel_SetBooleanByKey(uint32_t key, bool val)
{
    dm_val_t inval = { 0 };
    inval.bval = val;
    return DataModel_SetIntegralTypeByKey(key, inval);
}
{% endif %}
{% for t in int_types %}

DM_RETURN_CODE DataModel_Set{{ t.wrapper_suffix }}ByKey(uint32_t key, {{ t.c_type }} val)
{
    dm_val_t inval = { 0 };
    inval.{{ t.val_field }} = val;
    return DataModel_SetIntegralTypeByKey(key, inval);
}
{% endfor %}
{% if has_ro_strings or has_rw_strings %}

/* ---- String API ---- */

DM_RETURN_CODE DataModel_GetStringByKey(uint32_t key, const char **out_str)
{
    if (!dm_initialized) {
        return DM_RETURN_CODE_NOT_INITIALIZED;
    }
    if (!DM_IS_KEY_DATA_TYPE(key, DM_KEY_TYPE_STRING)) {
        return DM_RETURN_CODE_KEY_TYPE_INCORRECT;
    }
    if (out_str == NULL) {
        return DM_RETURN_CODE_OUTPUT_VARIABLE_NULL;
    }
{% if target.has_mutex %}
    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_lock }};
    }
{% endif %}
    bool ok = false;
{% if has_ro_strings and has_rw_strings %}
    if (DM_IS_KEY_READONLY(key)) {
        ok = StringStorage_GetReadOnlyKey(key, out_str);
    } else {
        ok = StringStorage_GetKey(key, out_str);
    }
{% elif has_ro_strings %}
    ok = StringStorage_GetReadOnlyKey(key, out_str);
{% else %}
    ok = StringStorage_GetKey(key, out_str);
{% endif %}
{% if target.has_mutex %}
    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_unlock }};
    }
{% endif %}
    return ok ? DM_RETURN_CODE_SUCCESS : DM_RETURN_CODE_STORAGE_LOOKUP_FAILURE;
}
{% endif %}
{% if has_rw_strings %}

DM_RETURN_CODE DataModel_SetStringByKey(uint32_t key, const char *val)
{
    if (!dm_initialized) {
        return DM_RETURN_CODE_NOT_INITIALIZED;
    }
    if (!DM_IS_KEY_DATA_TYPE(key, DM_KEY_TYPE_STRING)) {
        return DM_RETURN_CODE_KEY_TYPE_INCORRECT;
    }
    if (DM_IS_KEY_READONLY(key)) {
        return DM_RETURN_CODE_SET_ON_READONLY_KEY;
    }
{% if target.has_mutex %}
    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_lock }};
    }
{% endif %}
    bool ok = StringStorage_SetKey(key, val);
{% if target.has_mutex %}
    if (DM_IS_KEY_THREADSAFE(key)) {
        {{ target.mutex_unlock }};
    }
{% endif %}
{% if not no_events %}
    if (ok && dm_event_callback != NULL) {
        dm_event_callback(key);
    }
{% endif %}
    return ok ? DM_RETURN_CODE_SUCCESS : DM_RETURN_CODE_STORAGE_LOOKUP_FAILURE;
}
{% endif %}