/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_H
#define INGOT_DM_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#include "dm_key.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    DM_RETURN_CODE_SUCCESS              =  1,
    DM_RETURN_CODE_NOT_INITIALIZED      = -1,
    DM_RETURN_CODE_KEY_TYPE_INCORRECT   = -2,
    DM_RETURN_CODE_SET_ON_READONLY_KEY  = -3,
    DM_RETURN_CODE_STORAGE_LOOKUP_FAILURE = -4,
    DM_RETURN_CODE_SET_VALUE_UNCHANGED  = -5,
    DM_RETURN_CODE_NO_KEYS_OF_TYPE      = -6,
    DM_RETURN_CODE_OUTPUT_VARIABLE_NULL = -7,
{% if has_persistence %}
    DM_RETURN_CODE_PERSISTENCE_FILE_NOT_FOUND  = -8,
    DM_RETURN_CODE_PERSISTENCE_READ_FAILURE    = -9,
    DM_RETURN_CODE_PERSISTENCE_WRITE_FAILURE   = -10,
    DM_RETURN_CODE_PERSISTENCE_MAGIC_MISMATCH  = -11,
{% endif %}
} DM_RETURN_CODE;

typedef union {
    bool     bval;
    uint8_t  u8val;
    int8_t   s8val;
    uint16_t u16val;
    int16_t  s16val;
    uint32_t u32val;
    int32_t  s32val;
} dm_val_t;

{% if not no_events %}
typedef void (*DM_Event_Callback)(uint32_t key);

void DM_Initialize(DM_Event_Callback event_callback);
{% else %}
void DM_Initialize(void);
{% endif %}
void DM_TearDown(void);

/* Integral type dispatch (routes via key data_type bits) */
DM_RETURN_CODE DM_SetValComType(uint32_t key, dm_val_t inval);
dm_val_t       DM_GetValComType(uint32_t key);

/* Typed convenience setters */
{% if has_bool %}
DM_RETURN_CODE DM_SetValBit(uint32_t key, bool val);
{% endif %}
{% for t in int_types %}
DM_RETURN_CODE DM_SetVal{{ t.short_suffix }}(uint32_t key, {{ t.c_type }} val);
{% endfor %}

/* Typed convenience getters */
{% if has_bool %}
bool DM_GetValBit(uint32_t key);
{% endif %}
{% for t in int_types %}
{{ t.c_type }} DM_GetVal{{ t.short_suffix }}(uint32_t key);
{% endfor %}

/* String API */
{% if has_ro_strings or has_rw_strings %}
DM_RETURN_CODE DM_GetValStr(uint32_t key, const char **out_str);
{% endif %}
{% if has_rw_strings %}
DM_RETURN_CODE DM_SetValStr(uint32_t key, const char *val);
{% endif %}
{% if has_persistence %}

/* Persistence API */
DM_RETURN_CODE DM_LoadPersistentKeys(const char *filepath);
DM_RETURN_CODE DM_SavePersistentKeys(const char *filepath);
{% endif %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_H */