/**
 * @file          dm_enums.h
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_DM_ENUMS_H
#define INGOT_DM_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif
{% for e in enums %}
{%- if e.doc %}
/* {{ e.doc }} */
{%- endif %}
typedef enum {
{% for m in e.members %}    {{ m.name }} = {{ m.value }}{% if not loop.last %},{% endif %}
{% endfor %}} {{ e.type_name }};
{% endfor %}
#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_ENUMS_H */