/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_HELPERS_H
#define INGOT_DM_HELPERS_H

#include <stdbool.h>
#include <stdint.h>
#include "dm.h"
#include "dm_key_tbl.h"
{% if has_enum_helpers %}#include "dm_enums.h"
{% endif %}

#ifdef __cplusplus
extern "C" {
#endif
{% for h in helpers %}
{% if h.is_string %}

const char *DM_Get_{{ h.helper_name }}(void);
{% if not h.is_read_only %}
DM_RETURN_CODE DM_Set_{{ h.helper_name }}(const char *val);
{% endif %}
{% else %}

static inline {{ h.c_type }} DM_Get_{{ h.helper_name }}(void)
{
    dm_val_t val = DM_GetComType({{ h.define_name }});
    return {% if h.is_enum %}({{ h.c_type }})val.{{ h.val_field }}{% else %}val.{{ h.val_field }}{% endif %};
}
{% if not h.is_read_only %}
static inline DM_RETURN_CODE DM_Set_{{ h.helper_name }}({{ h.c_type }} x)
{
    dm_val_t val = { 0 };
    val.{{ h.val_field }} = {% if h.is_enum %}({{ h.storage_c_type }})x{% else %}x{% endif %};
    return DM_SetComType({{ h.define_name }}, val);
}
{% endif %}
{% endif %}
{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_HELPERS_H */