/**
 * @file          dm_helpers.c
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#include "dm_helpers.h"

{% for h in helpers -%}
{%- if h.is_string -%}
const char *DM_Get_{{ h.helper_name }}(void)
{
    const char *val = NULL;
    DM_GetValStr({{ h.define_name }}, &val);
    return val;
}
{% if not h.is_read_only %}
DM_RETURN_CODE DM_Set_{{ h.helper_name }}(const char *val)
{
    return DM_SetValStr({{ h.define_name }}, val);
}
{% endif %}
{% endif -%}
{%- endfor -%}