/**
 * @file          dm_key_tbl.h
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_DM_KEY_TBL_H
#define INGOT_DM_KEY_TBL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
{% for key in keys %}
/*
 * doc: {{ key.doc }}
 *name: {{ key.namespace }}.{{ key.class }}.{{ key.name }}
 *type: {{ key.type_name }}
 *unit: {{ key.unit }}
 *  ro: {{ key.read_only }} ts: {{ key.thread_safe }} ps: {{ key.persistent }} ev: {{ key.event }}
 */
#define {{ key.define_name }} {{ key.hex_value }}U
{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_KEY_TBL_H */