/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_KEY_H
#define INGOT_DM_KEY_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * 32-bit key encoding:
 *   [31:22] namespace (10 bits)
 *   [21:17] class     (5 bits)
 *   [16:7]  id        (10 bits, sequential within class)
 *   [6:3]   data_type (4 bits)
 *   [2]     thread_safe
 *   [1]     derived
 *   [0]     read_only
 */

typedef enum {
    DM_KEY_TYPE_BOOL   = 0,
    DM_KEY_TYPE_UINT8  = 1,
    DM_KEY_TYPE_UINT16 = 2,
    DM_KEY_TYPE_UINT32 = 3,
    DM_KEY_TYPE_INT8   = 4,
    DM_KEY_TYPE_INT16  = 5,
    DM_KEY_TYPE_INT32  = 6,
    /* 7 = float (reserved) */
    DM_KEY_TYPE_STRING = 8,
    DM_KEY_TYPE_BINARY = 9,
    DM_KEY_TYPE_MAX
} DM_KEY_TYPE;

typedef union {
    struct {
        unsigned int read_only    : 1;
        unsigned int derived      : 1;
        unsigned int thread_safe  : 1;
        unsigned int data_type    : 4;
        unsigned int id           : 10;
        unsigned int dt_class     : 5;
        unsigned int ns           : 10;
    } part;
    uint32_t val;
} DM_Key;

#define DM_IS_KEY_READONLY(k)          ((k) & 0x1U)
#define DM_IS_KEY_DERIVED(k)           (((k) >> 1) & 0x1U)
#define DM_IS_KEY_THREADSAFE(k)        (((k) >> 2) & 0x1U)
#define DM_KEY_GET_TYPE(k)             (((k) >> 3) & 0xFU)
#define DM_IS_KEY_DATA_TYPE(k, t)      (DM_KEY_GET_TYPE(k) == (uint32_t)(t))
#define DM_IS_KEY_IN_NAMESPACE(k, ns)  ((((k) >> 22) & 0x3FFU) == (uint32_t)(ns))

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_KEY_H */