/**
 * @file          dm_key_events_wrapper.hpp
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_DM_KEY_EVENTS_WRAPPER_H
#define INGOT_DM_KEY_EVENTS_WRAPPER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Fan a runtime key_id out to its typed tinyfsm event. C-linkage so the
 * C99 DM_Event_Callback (or a broker draining it) can call it. */
void send_tinyfsm_event_by_key(uint32_t key_id);

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_KEY_EVENTS_WRAPPER_H */