/**
 * @file          dm_key_events.hpp
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_DM_KEY_EVENTS_HPP
#define INGOT_DM_KEY_EVENTS_HPP

#include "tinyfsm.hpp"

#ifdef __cplusplus
extern "C" {
#endif
{% for group in groups %}

// namespace: {{ group.namespace }}, class: {{ group.class }}
{% for ev in group.events %}struct {{ ev }} : tinyfsm::Event { };
{% endfor %}{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_KEY_EVENTS_HPP */