/**
 * @file          dm_key_events_wrapper.cpp
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#include "dm_key_events_wrapper.hpp"

#include "api/dm_key_tbl.h"
#include "dm_key_events.hpp"

/* Consumer-provided seam: fsmlist.hpp must declare
 *   template<typename E> void send_tinyfsm_event(E const & event);
 * bound to the consumer's tinyfsm::FsmList. ingot does not know the
 * consumer's FSM inventory and never defines it. */
#include "fsmlist.hpp"

void send_tinyfsm_event_by_key(uint32_t key_id)
{
    switch (key_id) {
{%- for ev in events %}
        case {{ ev.define_name }}:
            send_tinyfsm_event({{ ev.fsm_event_name }}());
            break;
{%- endfor %}
        default:
            /* Do nothing */
            break;
    }
}