/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_KEY_TBL_H
#define INGOT_DM_KEY_TBL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
{% for key in keys %}

/* {{ key.namespace }}.{{ key.class }}.{{ key.name }}
 * type={{ key.type_name }}{% if key.unit %}, unit={{ key.unit }}{% endif %}{% if key.read_only %}, read_only{% endif %}{% if key.thread_safe %}, thread_safe{% endif %}{% if key.persistent %}, persistent{% endif %}{% if key.event %}, event{% endif %} */
#define {{ key.define_name }} {{ key.hex_value }}U
{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_KEY_TBL_H */