/**
 * @file          dm_ns.h
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_DM_NS_H
#define INGOT_DM_NS_H

#ifdef __cplusplus
extern "C" {
#endif
{% for ns in namespaces %}
#define DM_NS_{{ ns.namespace_upper }} {{ ns.ns_id }}U
{% endfor %}
#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_NS_H */