//! Generated by ingot v{{ version }} — {{ time }}.
#![no_std]
#![allow(clippy::missing_const_for_fn)]

/// Jenkins lookup3.c `final()` mix — matches the C backend's `jenkins_hash`.
const fn jenkins_hash(seed: u32, key: u32) -> u32 {
    let mut a: u32 = key;
    let mut b: u32 = seed;
    let mut c: u32 = 0x9e3779b9u32;

    c ^= b;
    c = c.wrapping_sub(b.rotate_left(14));
    a ^= c;
    a = a.wrapping_sub(c.rotate_left(11));
    b ^= a;
    b = b.wrapping_sub(a.rotate_left(25));
    c ^= b;
    c = c.wrapping_sub(b.rotate_left(16));
    a ^= c;
    a = a.wrapping_sub(c.rotate_left(4));
    b ^= a;
    b = b.wrapping_sub(a.rotate_left(14));
    c ^= b;
    c = c.wrapping_sub(b.rotate_left(24));

    c
}

fn hash_index(seed1: u32, seed2: u32, g: &[i32], num_keys: usize, key: u32) -> usize {
    let n = g.len() as u32;
    let h1 = (jenkins_hash(seed1, key) % n) as usize;
    let h2 = (jenkins_hash(seed2, key) % n) as usize;
    let sum = g[h1] as i64 + g[h2] as i64;
    sum.rem_euclid(num_keys as i64) as usize
}
{% for c in key_consts %}
pub const {{ c.const_name }}: u32 = {{ c.hex_value }};
{% endfor %}

pub const PERSISTENT_KEYS: &[u32] = &[
{% for name in persistent_key_names %}    {{ name }},
{% endfor %}];
{% for e in enums %}
{%- if e.doc %}
/// {{ e.doc }}
{%- endif %}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr({{ e.repr }})]
pub enum {{ e.type_name }} {
{% for m in e.members %}    {{ m.name }} = {{ m.value }},
{% endfor %}}

impl {{ e.type_name }} {
    /// Maps a raw storage value back to a variant, falling back to
    /// `{{ e.fallback_name }}` for a value that matches no member (only
    /// reachable via the generic by-key API, which bypasses this type).
    pub const fn from_raw(v: {{ e.repr }}) -> Self {
        match v {
{% for m in e.members %}            {{ m.value }} => Self::{{ m.name }},
{% endfor %}            _ => Self::{{ e.fallback_name }},
        }
    }

    pub const fn to_raw(self) -> {{ e.repr }} {
        self as {{ e.repr }}
    }
}
{% endfor %}
{% for g in int_groups %}
const {{ g.field_name | upper }}_SEED_1: u32 = {{ g.seed1 }};
const {{ g.field_name | upper }}_SEED_2: u32 = {{ g.seed2 }};
const {{ g.field_name | upper }}_G: [i32; {{ g.g_size }}] = [{{ g.g_table_str }}];
const {{ g.field_name | upper }}_KEYS: [u32; {{ g.num_keys }}] = [{{ g.keys_table_str }}];
const {{ g.field_name | upper }}_DEFAULTS: [{{ g.rust_type }}; {{ g.num_keys }}] = [{{ g.default_table_str }}];
{% endfor %}
{% if bool_group %}
const BOOL_VALUES_SEED_1: u32 = {{ bool_group.seed1 }};
const BOOL_VALUES_SEED_2: u32 = {{ bool_group.seed2 }};
const BOOL_VALUES_G: [i32; {{ bool_group.g_size }}] = [{{ bool_group.g_table_str }}];
const BOOL_VALUES_KEYS: [u32; {{ bool_group.num_keys }}] = [{{ bool_group.keys_table_str }}];
const BOOL_VALUES_DEFAULTS: [bool; {{ bool_group.num_keys }}] = [{{ bool_group.default_table_str }}];
{% endif %}

/// The data model: one field per storage group, addressable either by the
/// named accessor methods below or, for scalar types, by encoded key via
/// the generic `get_*`/`set_*` methods.
#[derive(Debug, Clone)]
pub struct DataModel {
{% for g in int_groups %}    {{ g.field_name }}: [{{ g.rust_type }}; {{ g.num_keys }}],
{% endfor %}{% if bool_group %}    bool_values: [bool; {{ bool_group.num_keys }}],
{% endif %}{% for a in bytes_accessors %}    {{ a.field_name }}: [u8; {{ a.max_size }}],
{% endfor %}}

impl Default for DataModel {
    fn default() -> Self {
        Self::new()
    }
}

impl DataModel {
    pub const fn new() -> Self {
        Self {
{% for g in int_groups %}            {{ g.field_name }}: {{ g.field_name | upper }}_DEFAULTS,
{% endfor %}{% if bool_group %}            bool_values: BOOL_VALUES_DEFAULTS,
{% endif %}{% for a in bytes_accessors %}            {{ a.field_name }}: {
                let mut buf = [0u8; {{ a.max_size }}];
                let src: &[u8] = {{ a.default_literal }};
                let mut i = 0;
                while i < src.len() {
                    buf[i] = src[i];
                    i += 1;
                }
                buf
            },
{% endfor %}        }
    }
{% for a in int_accessors %}
{% if a.enum_type %}
    pub fn {{ a.method_name }}(&self) -> {{ a.enum_type }} {
        {{ a.enum_type }}::from_raw(self.{{ a.field_name }}[{{ a.idx }}] as {{ a.enum_repr }})
    }
{% if not a.read_only %}
    pub fn set_{{ a.method_name }}(&mut self, value: {{ a.enum_type }}) {
        self.{{ a.field_name }}[{{ a.idx }}] = value.to_raw() as {{ a.rust_type }};
    }
{% endif %}
{% else %}
    pub fn {{ a.method_name }}(&self) -> {{ a.rust_type }} {
        self.{{ a.field_name }}[{{ a.idx }}]
    }
{% if not a.read_only %}
    pub fn set_{{ a.method_name }}(&mut self, value: {{ a.rust_type }}) {
        self.{{ a.field_name }}[{{ a.idx }}] = value;
    }
{% endif %}
{% endif %}
{% endfor %}
{% for a in bool_accessors %}
    pub fn {{ a.method_name }}(&self) -> bool {
        self.bool_values[{{ a.idx }}]
    }
{% if not a.read_only %}
    pub fn set_{{ a.method_name }}(&mut self, value: bool) {
        self.bool_values[{{ a.idx }}] = value;
    }
{% endif %}{% endfor %}
{% for a in bytes_accessors %}
{% if a.is_binary %}
    pub fn {{ a.method_name }}(&self) -> &[u8] {
        &self.{{ a.field_name }}
    }
{% else %}
    /// Returns the stored bytes up to the first `0` byte (mirrors the C
    /// backend treating this storage as a null-terminated C string).
    pub fn {{ a.method_name }}(&self) -> &[u8] {
        let buf = &self.{{ a.field_name }};
        let len = buf.iter().position(|&b| b == 0).unwrap_or(buf.len());
        &buf[..len]
    }
{% endif %}
{% if not a.read_only %}
    /// Copies up to `{{ a.max_size }}` bytes of `value` in, zero-padded.
    /// Returns `false` (and stores nothing) if `value` doesn't fit.
    pub fn set_{{ a.method_name }}(&mut self, value: &[u8]) -> bool {
        if value.len() > {{ a.max_size }} {
            return false;
        }
        self.{{ a.field_name }} = [0u8; {{ a.max_size }}];
        self.{{ a.field_name }}[..value.len()].copy_from_slice(value);
        true
    }
{% endif %}{% endfor %}
{% for g in int_groups %}
    pub fn get_{{ g.field_name }}(&self, key: u32) -> Option<{{ g.rust_type }}> {
        let idx = hash_index({{ g.field_name | upper }}_SEED_1, {{ g.field_name | upper }}_SEED_2, &{{ g.field_name | upper }}_G, {{ g.num_keys }}, key);
        if {{ g.field_name | upper }}_KEYS[idx] != key {
            return None;
        }
        Some(self.{{ g.field_name }}[idx])
    }

    pub fn set_{{ g.field_name }}(&mut self, key: u32, value: {{ g.rust_type }}) -> bool {
        let idx = hash_index({{ g.field_name | upper }}_SEED_1, {{ g.field_name | upper }}_SEED_2, &{{ g.field_name | upper }}_G, {{ g.num_keys }}, key);
        if {{ g.field_name | upper }}_KEYS[idx] != key {
            return false;
        }
        self.{{ g.field_name }}[idx] = value;
        true
    }
{% endfor %}
{% if bool_group %}
    pub fn get_bool_values(&self, key: u32) -> Option<bool> {
        let idx = hash_index(BOOL_VALUES_SEED_1, BOOL_VALUES_SEED_2, &BOOL_VALUES_G, {{ bool_group.num_keys }}, key);
        if BOOL_VALUES_KEYS[idx] != key {
            return None;
        }
        Some(self.bool_values[idx])
    }

    pub fn set_bool_values(&mut self, key: u32, value: bool) -> bool {
        let idx = hash_index(BOOL_VALUES_SEED_1, BOOL_VALUES_SEED_2, &BOOL_VALUES_G, {{ bool_group.num_keys }}, key);
        if BOOL_VALUES_KEYS[idx] != key {
            return false;
        }
        self.bool_values[idx] = value;
        true
    }
{% endif %}
}

#[cfg(test)]
mod tests {
    use super::*;

{% for g in int_groups %}
    #[test]
    fn {{ g.field_name }}_perfect_hash_is_unique() {
        let mut seen = [false; {{ g.num_keys }}];
        for &k in {{ g.field_name | upper }}_KEYS.iter() {
            let idx = hash_index({{ g.field_name | upper }}_SEED_1, {{ g.field_name | upper }}_SEED_2, &{{ g.field_name | upper }}_G, {{ g.num_keys }}, k);
            assert!(!seen[idx], "duplicate hash index for {{ g.field_name }}");
            seen[idx] = true;
        }
    }
{% endfor %}
{% if bool_group %}
    #[test]
    fn bool_values_perfect_hash_is_unique() {
        let mut seen = [false; {{ bool_group.num_keys }}];
        for &k in BOOL_VALUES_KEYS.iter() {
            let idx = hash_index(BOOL_VALUES_SEED_1, BOOL_VALUES_SEED_2, &BOOL_VALUES_G, {{ bool_group.num_keys }}, k);
            assert!(!seen[idx], "duplicate hash index for bool_values");
            seen[idx] = true;
        }
    }
{% endif %}
{% for a in int_accessors %}
{% if a.enum_type %}
    #[test]
    fn {{ a.method_name }}_roundtrip() {
        let {% if not a.read_only %}mut {% endif %}dm = DataModel::new();
        let before = dm.{{ a.method_name }}();
        assert_eq!(dm.get_{{ a.field_name }}({{ a.const_name }}), Some(before.to_raw()));
{% if not a.read_only %}
        let next_raw: {{ a.rust_type }} = if before.to_raw() == 0 { 1 } else { 0 };
        let next = {{ a.enum_type }}::from_raw(next_raw as {{ a.enum_repr }});
        dm.set_{{ a.method_name }}(next);
        assert_eq!(dm.{{ a.method_name }}().to_raw(), next.to_raw());
        assert!(dm.set_{{ a.field_name }}({{ a.const_name }}, before.to_raw()));
        assert_eq!(dm.{{ a.method_name }}().to_raw(), before.to_raw());
{% endif %}
    }
{% else %}
    #[test]
    fn {{ a.method_name }}_roundtrip() {
        let {% if not a.read_only %}mut {% endif %}dm = DataModel::new();
        let before = dm.{{ a.method_name }}();
        assert_eq!(dm.get_{{ a.field_name }}({{ a.const_name }}), Some(before));
{% if not a.read_only %}
        let next: {{ a.rust_type }} = if before == 0 { 1 } else { 0 };
        dm.set_{{ a.method_name }}(next);
        assert_eq!(dm.{{ a.method_name }}(), next);
        assert!(dm.set_{{ a.field_name }}({{ a.const_name }}, before));
        assert_eq!(dm.{{ a.method_name }}(), before);
{% endif %}
    }
{% endif %}
{% endfor %}
{% for a in bool_accessors %}
    #[test]
    fn {{ a.method_name }}_roundtrip() {
        let {% if not a.read_only %}mut {% endif %}dm = DataModel::new();
        let before = dm.{{ a.method_name }}();
        assert_eq!(dm.get_bool_values({{ a.const_name }}), Some(before));
{% if not a.read_only %}
        dm.set_{{ a.method_name }}(!before);
        assert_eq!(dm.{{ a.method_name }}(), !before);
        assert!(dm.set_bool_values({{ a.const_name }}, before));
        assert_eq!(dm.{{ a.method_name }}(), before);
{% endif %}
    }
{% endfor %}
{% for a in bytes_accessors %}
    #[test]
    fn {{ a.method_name }}_roundtrip() {
        let {% if not a.read_only %}mut {% endif %}dm = DataModel::new();
        let default_value: &[u8] = {{ a.default_literal }};
        assert_eq!(dm.{{ a.method_name }}(), default_value);
{% if not a.read_only %}
        assert!(dm.set_{{ a.method_name }}(b"x"));
        assert_eq!(dm.{{ a.method_name }}(), b"x");
        assert!(dm.set_{{ a.method_name }}(default_value));
{% endif %}
    }
{% endfor %}
}