/**
 * @file          integer_storage.c
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#include <stddef.h>
#include "integer_storage.h"
#include "core/jenkins_hash.h"
{%- for t in types %}

/* ---- {{ t.label }} storage ({{ t.num_keys }} keys) ---- */

#define {{ t.PREFIX }}_HASH_SEED_1 {{ t.seed1 }}U
#define {{ t.PREFIX }}_HASH_SEED_2 {{ t.seed2 }}U
#define {{ t.PREFIX }}_HASH_G_SIZE {{ t.g_size }}U

#define {{ t.PREFIX }}_HASH_INDEX(key, seed) \
    {{ t.prefix }}_G[jenkins_hash(seed, key) % {{ t.PREFIX }}_HASH_G_SIZE]

static const {{ t.g_c_type }} {{ t.prefix }}_G[{{ t.PREFIX }}_HASH_G_SIZE] = {
    {{ t.g_table_str }}
};

static {{ t.c_type }} {{ t.prefix }}_storage[{{ t.PREFIX }}_STORAGE_NUM_KEYS] = {
    {{ t.init_table_str }}
};

bool IntegerStorage_Set{{ t.suffix }}Key(uint32_t key, {{ t.c_type }} value)
{
    uint32_t index = ({{ t.PREFIX }}_HASH_INDEX(key, {{ t.PREFIX }}_HASH_SEED_1)
                    + {{ t.PREFIX }}_HASH_INDEX(key, {{ t.PREFIX }}_HASH_SEED_2))
                    % {{ t.PREFIX }}_STORAGE_NUM_KEYS;
    {{ t.prefix }}_storage[index] = value;
    return true;
}

bool IntegerStorage_Get{{ t.suffix }}Key(uint32_t key, {{ t.c_type }} *result)
{
    if (result == NULL) {
        return false;
    }
    uint32_t index = ({{ t.PREFIX }}_HASH_INDEX(key, {{ t.PREFIX }}_HASH_SEED_1)
                    + {{ t.PREFIX }}_HASH_INDEX(key, {{ t.PREFIX }}_HASH_SEED_2))
                    % {{ t.PREFIX }}_STORAGE_NUM_KEYS;
    *result = {{ t.prefix }}_storage[index];
    return true;
}
{%- endfor %}