/**
 * @file          jenkins_hash.c
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#include "jenkins_hash.h"

#define rot(x, k) (((x) << (k)) | ((x) >> (32 - (k))))

uint32_t jenkins_hash(uint32_t seed, uint32_t key)
{
    uint32_t a = key;
    uint32_t b = seed;
    uint32_t c = 0x9e3779b9u;

    c ^= b; c -= rot(b, 14);
    a ^= c; a -= rot(c, 11);
    b ^= a; b -= rot(a, 25);
    c ^= b; c -= rot(b, 16);
    a ^= c; a -= rot(c, 4);
    b ^= a; b -= rot(a, 14);
    c ^= b; c -= rot(b, 24);

    return c;
}