/**
 * @file          jenkins_hash.h
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_JENKINS_HASH_H
#define INGOT_JENKINS_HASH_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uint32_t jenkins_hash(uint32_t seed, uint32_t key);

#ifdef __cplusplus
}
#endif

#endif /* INGOT_JENKINS_HASH_H */