/* Generated by ingot v{{ version }} — do not edit */
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "persistence_storage.h"
#include "api/key_definitions.h"

/* ---- Packed persistence struct ---- */

#pragma pack(push, 1)
typedef struct {
    uint32_t magic;
{% for e in persistence.entries %}
{% if e.is_string %}
    char {{ e.field_name }}[{{ e.max_size }}];
{% else %}
    {{ e.c_type }} {{ e.field_name }};
{% endif %}
{% endfor %}
} PersistenceStorage_T;
#pragma pack(pop)

static PersistenceStorage_T persistence_data = {
    .magic = (sizeof(PersistenceStorage_T) ^ NUM_PERSISTENCE_KEYS),
{% for e in persistence.entries %}
{% if e.is_string %}
    .{{ e.field_name }} = {{ e.default_literal }},
{% else %}
    .{{ e.field_name }} = {{ e.default_literal }},
{% endif %}
{% endfor %}
};

/* ---- Key query ---- */

bool PersistenceStorage_IsKeyPersistent(uint32_t key)
{
    switch (key) {
{% for e in persistence.entries %}
    case {{ e.define_name }}:
{% endfor %}
        return true;
    default:
        return false;
    }
}

/* ---- Sync: struct → live storage ---- */

static void PersistenceStorage_SyncToStorage(void)
{
{% for e in persistence.entries %}
{% if e.is_string %}
    DataModel_SetStringByKey({{ e.define_name }}, persistence_data.{{ e.field_name }});
{% else %}
    {
        dm_val_t v = { 0 };
        v.{{ e.val_field }} = persistence_data.{{ e.field_name }};
        DataModel_SetIntegralTypeByKey({{ e.define_name }}, v);
    }
{% endif %}
{% endfor %}
}

/* ---- Sync: live storage → struct ---- */

static void PersistenceStorage_SyncFromStorage(void)
{
{% for e in persistence.entries %}
{% if e.is_string %}
    {
        const char *s = NULL;
        if (DataModel_GetStringByKey({{ e.define_name }}, &s) == DM_RETURN_CODE_SUCCESS && s != NULL) {
            strncpy(persistence_data.{{ e.field_name }}, s, sizeof(persistence_data.{{ e.field_name }}) - 1);
            persistence_data.{{ e.field_name }}[sizeof(persistence_data.{{ e.field_name }}) - 1] = '\0';
        }
    }
{% else %}
    {
        dm_val_t v = DataModel_GetIntegralTypeByKey({{ e.define_name }});
        persistence_data.{{ e.field_name }} = v.{{ e.val_field }};
    }
{% endif %}
{% endfor %}
}

/* ---- File I/O ---- */

DM_RETURN_CODE DataModel_LoadPersistentKeys(const char *filepath)
{
    const char *path = (filepath != NULL) ? filepath : DEFAULT_DM_FILENAME;
    FILE *f = fopen(path, "rb");

    if (f == NULL) {
        return DM_RETURN_CODE_PERSISTENCE_FILE_NOT_FOUND;
    }

    PersistenceStorage_T tmp;
    size_t n = fread(&tmp, sizeof(PersistenceStorage_T), 1, f);
    fclose(f);

    if (n != 1) {
        return DM_RETURN_CODE_PERSISTENCE_READ_FAILURE;
    }

    uint32_t expected_magic = (sizeof(PersistenceStorage_T) ^ NUM_PERSISTENCE_KEYS);
    if (tmp.magic != expected_magic) {
        return DM_RETURN_CODE_PERSISTENCE_MAGIC_MISMATCH;
    }

    persistence_data = tmp;
    PersistenceStorage_SyncToStorage();

    return DM_RETURN_CODE_SUCCESS;
}

DM_RETURN_CODE DataModel_SavePersistentKeys(const char *filepath)
{
    const char *path = (filepath != NULL) ? filepath : DEFAULT_DM_FILENAME;

    PersistenceStorage_SyncFromStorage();

    FILE *f = fopen(path, "wb");
    if (f == NULL) {
        return DM_RETURN_CODE_PERSISTENCE_WRITE_FAILURE;
    }

    size_t n = fwrite(&persistence_data, sizeof(PersistenceStorage_T), 1, f);
    fclose(f);

    if (n != 1) {
        return DM_RETURN_CODE_PERSISTENCE_WRITE_FAILURE;
    }

    return DM_RETURN_CODE_SUCCESS;
}