/**
 * @file          persistence_storage.h
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_PERSISTENCE_STORAGE_H
#define INGOT_PERSISTENCE_STORAGE_H

#include <stdint.h>
#include <stdbool.h>

#include "api/dm.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DEFAULT_DM_FILENAME
#define DEFAULT_DM_FILENAME "/sdcard/dm.bin"
#endif

#define NUM_PERSISTENCE_KEYS {{ persistence.num_keys }}U

/**
 * Check whether a key is persistent.
 *
 * @param key  Encoded 32-bit data model key.
 * @return true if the key is in the persistence set.
 */
bool PersistenceStorage_IsKeyPersistent(uint32_t key);

/**
 * Load persistent keys from a binary file and push values into live storage.
 *
 * @param filepath  Path to binary file, or NULL for DEFAULT_DM_FILENAME.
 * @return DM_RETURN_CODE_SUCCESS on success.
 */
DM_RETURN_CODE DM_LoadPersistentKeys(const char *filepath);

/**
 * Save current persistent key values from live storage to a binary file.
 *
 * @param filepath  Path to binary file, or NULL for DEFAULT_DM_FILENAME.
 * @return DM_RETURN_CODE_SUCCESS on success.
 */
DM_RETURN_CODE DM_SavePersistentKeys(const char *filepath);

#ifdef __cplusplus
}
#endif

#endif /* INGOT_PERSISTENCE_STORAGE_H */