/**
 * @file          string_storage.h
 * @brief         Generated by ingot v{{ version }}
 * @version       v{{ version }}
 * @date          {{ time }}
 * @history:
 * Date           Version        Author    Description
 * {{ time }}     v{{ version }}         ingot     Generated by ingot v{{ version }}
 */
#ifndef INGOT_STRING_STORAGE_H
#define INGOT_STRING_STORAGE_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif
{% if ro %}

/* Read-only string storage: {{ ro.num_keys }} keys */
#define RO_STRING_STORAGE_NUM_KEYS {{ ro.num_keys }}U

bool StringStorage_GetReadOnlyKey(uint32_t key, const char **result);
{% endif -%}
{%- if rw %}

/* Read-write string storage: {{ rw.num_keys }} keys */
#define RW_STRING_STORAGE_NUM_KEYS {{ rw.num_keys }}U

bool StringStorage_SetKey(uint32_t key, const char *value);
bool StringStorage_GetKey(uint32_t key, const char **result);
uint16_t StringStorage_GetMaxSize(uint32_t key);
{% endif %}

#define STRING_STORAGE_NUM_KEYS {{ total_keys }}U

#ifdef __cplusplus
}
#endif

#endif /* INGOT_STRING_STORAGE_H */