/* Generated by ingot v{{ version }} — do not edit */
#include <stddef.h>
#include <string.h>
#include "string_storage.h"
#include "core/jenkins_hash.h"
{% if ro %}

/* ---- Read-only string storage ({{ ro.num_keys }} keys) ---- */

#define RO_STR_HASH_SEED_1 {{ ro.seed1 }}U
#define RO_STR_HASH_SEED_2 {{ ro.seed2 }}U
#define RO_STR_HASH_G_SIZE {{ ro.g_size }}U

#define RO_STR_HASH_INDEX(key, seed) \
    ro_str_G[jenkins_hash(seed, key) % RO_STR_HASH_G_SIZE]

static const {{ ro.g_c_type }} ro_str_G[RO_STR_HASH_G_SIZE] = {
    {{ ro.g_table_str }}
};

static const char * const ro_strings[RO_STRING_STORAGE_NUM_KEYS] = {
{% for e in ro.entries %}    {{ e.default_literal }}{% if not loop.last %},{% endif %}

{% endfor %}};

bool StringStorage_GetReadOnlyKey(uint32_t key, const char **result)
{
    if (result == NULL) {
        return false;
    }
    uint32_t index = (RO_STR_HASH_INDEX(key, RO_STR_HASH_SEED_1)
                    + RO_STR_HASH_INDEX(key, RO_STR_HASH_SEED_2))
                    % RO_STRING_STORAGE_NUM_KEYS;
    *result = ro_strings[index];
    return true;
}
{% endif %}
{% if rw %}

/* ---- Read-write string storage ({{ rw.num_keys }} keys) ---- */

#define RW_STR_HASH_SEED_1 {{ rw.seed1 }}U
#define RW_STR_HASH_SEED_2 {{ rw.seed2 }}U
#define RW_STR_HASH_G_SIZE {{ rw.g_size }}U

#define RW_STR_HASH_INDEX(key, seed) \
    rw_str_G[jenkins_hash(seed, key) % RW_STR_HASH_G_SIZE]

static const {{ rw.g_c_type }} rw_str_G[RW_STR_HASH_G_SIZE] = {
    {{ rw.g_table_str }}
};
{% for e in rw.entries %}
static char rw_str_{{ e.idx }}[{{ e.max_size }}] = {{ e.default_literal }};
{% endfor %}

static char *rw_string_ptrs[RW_STRING_STORAGE_NUM_KEYS] = {
{% for e in rw.entries %}    rw_str_{{ e.idx }}{% if not loop.last %},{% endif %}

{% endfor %}};

static const uint16_t rw_max_sizes[RW_STRING_STORAGE_NUM_KEYS] = {
{% for e in rw.entries %}    {{ e.max_size }}{% if not loop.last %},{% endif %}

{% endfor %}};

bool StringStorage_SetKey(uint32_t key, const char *value)
{
    uint32_t index = (RW_STR_HASH_INDEX(key, RW_STR_HASH_SEED_1)
                    + RW_STR_HASH_INDEX(key, RW_STR_HASH_SEED_2))
                    % RW_STRING_STORAGE_NUM_KEYS;
    uint16_t max_size = rw_max_sizes[index];
    if (value == NULL) {
        memset(rw_string_ptrs[index], 0, max_size);
        return true;
    }
    uint32_t len = (uint32_t)strlen(value);
    if (len >= max_size) {
        return false;
    }
    memset(rw_string_ptrs[index], 0, max_size);
    memcpy(rw_string_ptrs[index], value, len);
    return true;
}

bool StringStorage_GetKey(uint32_t key, const char **result)
{
    if (result == NULL) {
        return false;
    }
    uint32_t index = (RW_STR_HASH_INDEX(key, RW_STR_HASH_SEED_1)
                    + RW_STR_HASH_INDEX(key, RW_STR_HASH_SEED_2))
                    % RW_STRING_STORAGE_NUM_KEYS;
    *result = rw_string_ptrs[index];
    return true;
}

uint16_t StringStorage_GetMaxSize(uint32_t key)
{
    uint32_t index = (RW_STR_HASH_INDEX(key, RW_STR_HASH_SEED_1)
                    + RW_STR_HASH_INDEX(key, RW_STR_HASH_SEED_2))
                    % RW_STRING_STORAGE_NUM_KEYS;
    return rw_max_sizes[index];
}
{% endif %}