/* Generated by ingot v{{ version }} — do not edit */
#include <stdio.h>
#include "unity.h"
#include "api/dm.h"
#include "api/dm_key.h"
#include "api/dm_key_tbl.h"
{% if has_persistence %}
#include "storage/persistence_storage.h"
{% endif %}

{% if not no_events %}
static void dummy_event_callback(uint32_t key) { (void)key; }
{% endif %}

void setUp(void) {
{% if not no_events %}
    DM_Initialize(dummy_event_callback);
{% else %}
    DM_Initialize();
{% endif %}
}

void tearDown(void) {
    DM_TearDown();
}

/* ---- Default value tests ---- */
{% for k in keys %}
{% if k.is_string %}
void test_default_{{ k.define_name }}(void)
{
    const char *val = NULL;
    DM_RETURN_CODE rc = DM_GetStr({{ k.define_name }}, &val);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SUCCESS, rc);
    TEST_ASSERT_NOT_NULL(val);
    TEST_ASSERT_EQUAL_STRING({{ k.default_c }}, val);
}
{% elif k.is_bool %}
void test_default_{{ k.define_name }}(void)
{
    dm_val_t val = DM_GetComType({{ k.define_name }});
    TEST_ASSERT_EQUAL({{ k.default_c }}, val.{{ k.val_field }});
}
{% else %}
void test_default_{{ k.define_name }}(void)
{
    dm_val_t val = DM_GetComType({{ k.define_name }});
    TEST_ASSERT_EQUAL_INT({{ k.default_c }}, (int)val.{{ k.val_field }});
}
{% endif %}
{% endfor %}

/* ---- Set/Get roundtrip tests ---- */
{% for k in keys %}
{% if not k.read_only %}
{% if k.is_string %}
void test_roundtrip_{{ k.define_name }}(void)
{
    DM_RETURN_CODE rc = DM_SetStr({{ k.define_name }}, {{ k.test_c }});
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SUCCESS, rc);
    const char *val = NULL;
    rc = DM_GetStr({{ k.define_name }}, &val);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SUCCESS, rc);
    TEST_ASSERT_EQUAL_STRING({{ k.test_c }}, val);
}
{% elif k.is_bool %}
void test_roundtrip_{{ k.define_name }}(void)
{
    dm_val_t inval = { 0 };
    inval.{{ k.val_field }} = {{ k.test_c }};
    DM_RETURN_CODE rc = DM_SetComType({{ k.define_name }}, inval);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SUCCESS, rc);
    dm_val_t out = DM_GetComType({{ k.define_name }});
    TEST_ASSERT_EQUAL({{ k.test_c }}, out.{{ k.val_field }});
}
{% else %}
void test_roundtrip_{{ k.define_name }}(void)
{
    dm_val_t inval = { 0 };
    inval.{{ k.val_field }} = {{ k.test_c }};
    DM_RETURN_CODE rc = DM_SetComType({{ k.define_name }}, inval);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SUCCESS, rc);
    dm_val_t out = DM_GetComType({{ k.define_name }});
    TEST_ASSERT_EQUAL_INT({{ k.test_c }}, (int)out.{{ k.val_field }});
}
{% endif %}
{% endif %}
{% endfor %}

/* ---- Read-only rejection tests ---- */
{% for k in keys %}
{% if k.read_only and not k.is_string %}
void test_readonly_{{ k.define_name }}(void)
{
    dm_val_t inval = { 0 };
    DM_RETURN_CODE rc = DM_SetComType({{ k.define_name }}, inval);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SET_ON_READONLY_KEY, rc);
}
{% endif %}
{% endfor %}

/* ---- Unchanged value tests ---- */
{% for k in keys %}
{% if not k.read_only and not k.is_string %}
void test_unchanged_{{ k.define_name }}(void)
{
    dm_val_t val = DM_GetComType({{ k.define_name }});
    DM_RETURN_CODE rc = DM_SetComType({{ k.define_name }}, val);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SET_VALUE_UNCHANGED, rc);
}
{% endif %}
{% endfor %}

{% if has_persistence %}
/* ---- Persistence tests ---- */

void test_persistence_file_not_found(void)
{
    DM_RETURN_CODE rc = DM_LoadPersistentKeys("/tmp/ingot_nonexistent_dm.bin");
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_PERSISTENCE_FILE_NOT_FOUND, rc);
}

void test_persistence_save_load_roundtrip(void)
{
    const char *path = "/tmp/ingot_test_dm.bin";

{% for e in persistence_entries %}
{% if e.is_string %}
    DM_SetStr({{ e.define_name }}, {{ e.test_c }});
{% elif e.is_bool %}
    {
        dm_val_t v = { 0 };
        v.{{ e.val_field }} = {{ e.test_c }};
        DM_SetComType({{ e.define_name }}, v);
    }
{% else %}
    {
        dm_val_t v = { 0 };
        v.{{ e.val_field }} = {{ e.test_c }};
        DM_SetComType({{ e.define_name }}, v);
    }
{% endif %}
{% endfor %}

    /* Save current state */
    DM_RETURN_CODE rc = DM_SavePersistentKeys(path);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SUCCESS, rc);

    /* Set values back to defaults (storage arrays are static, TearDown doesn't reset) */
{% for e in persistence_entries %}
{% if e.is_string %}
    DM_SetStr({{ e.define_name }}, {{ e.default_c }});
{% else %}
    {
        dm_val_t d = { 0 };
        d.{{ e.val_field }} = {{ e.default_c }};
        DM_SetComType({{ e.define_name }}, d);
    }
{% endif %}
{% endfor %}

    /* Verify defaults are back */
{% for e in persistence_entries %}
{% if e.is_string %}
    {
        const char *s = NULL;
        DM_GetStr({{ e.define_name }}, &s);
        TEST_ASSERT_EQUAL_STRING({{ e.default_c }}, s);
    }
{% elif e.is_bool %}
    {
        dm_val_t dv = DM_GetComType({{ e.define_name }});
        TEST_ASSERT_EQUAL({{ e.default_c }}, dv.{{ e.val_field }});
    }
{% else %}
    {
        dm_val_t dv = DM_GetComType({{ e.define_name }});
        TEST_ASSERT_EQUAL_INT({{ e.default_c }}, (int)dv.{{ e.val_field }});
    }
{% endif %}
{% endfor %}

    /* Load saved state */
    rc = DM_LoadPersistentKeys(path);
    TEST_ASSERT_EQUAL(DM_RETURN_CODE_SUCCESS, rc);

    /* Verify restored values */
{% for e in persistence_entries %}
{% if e.is_string %}
    {
        const char *s = NULL;
        DM_GetStr({{ e.define_name }}, &s);
        TEST_ASSERT_EQUAL_STRING({{ e.test_c }}, s);
    }
{% elif e.is_bool %}
    {
        dm_val_t rv = DM_GetComType({{ e.define_name }});
        TEST_ASSERT_EQUAL({{ e.test_c }}, rv.{{ e.val_field }});
    }
{% else %}
    {
        dm_val_t rv = DM_GetComType({{ e.define_name }});
        TEST_ASSERT_EQUAL_INT({{ e.test_c }}, (int)rv.{{ e.val_field }});
    }
{% endif %}
{% endfor %}

    /* Cleanup */
    remove(path);
}
{% endif %}

int main(void)
{
    UNITY_BEGIN();
{% for k in keys %}
    RUN_TEST(test_default_{{ k.define_name }});
{% endfor %}
{% for k in keys %}
{% if not k.read_only %}
    RUN_TEST(test_roundtrip_{{ k.define_name }});
{% endif %}
{% endfor %}
{% for k in keys %}
{% if k.read_only and not k.is_string %}
    RUN_TEST(test_readonly_{{ k.define_name }});
{% endif %}
{% endfor %}
{% for k in keys %}
{% if not k.read_only and not k.is_string %}
    RUN_TEST(test_unchanged_{{ k.define_name }});
{% endif %}
{% endfor %}
{% if has_persistence %}
    RUN_TEST(test_persistence_file_not_found);
    RUN_TEST(test_persistence_save_load_roundtrip);
{% endif %}
    return UNITY_END();
}